### ISSUE TITLE
more of a question for you Azuraji

### ISSUE THREAD

**Issue by rmtaft** [azuraji/SLDataText#3]
I'm trying to use a bit of code to pull and set profiles from SLDataText. but for some reason I'm getting a doesn't exist kind of error. could you take a look and tell me how I'm to call out the config profile so I can set it.

ive been fighting with this for days, there had to be a way to tell the game that this is the profile I want to use

```
if  IsAddOnLoaded("SLDataText") then
    SLDataText:SetProfile("Profile - Server");  --- maybe just custom like  ("PD")
end
```

**Comment by azuraji** [comment]
You were quite close! The profiles reside under the `db` index so use `SLDataText.db:SetProfile("Profile1")` to change profiles.

**Comment by rmtaft** [comment]
well thank you kindly sir. i imagine i would have eventually gotten that, you just made my life a bunch easier
