### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by glyneth** [azuraji/SLDataText#5]
I've had memory crashes, and recently Details informed me that one of my addons was causing an issue, and to use the /details perf command to see it, and this is what came up:

["1"] = "Stuttering Information:",
["2"] = "An addon feature, script is using: _G.UpdateAddOnMemoryUsage()",
["3"] = "",
["4"] = "Description: Calculates memory usage of addons",
["5"] = "",
["6"] = "You may first: disable the addon feature that uses the functionality.",
["7"] = "Second: disable a script which are using the function call: _G.UpdateAddOnMemoryUsage().",
["8"] = "",
["9"] = "Callstack for Debug:",
["10"] = "[string "@Interface/AddOns/SLDataText/Elements/memory.lua"]:94: in function `Refresh'",
["11"] = "[string "@Interface/AddOns/SLDataText/Elements/memory.lua"]:64: in function <Interface/AddOns/SLDataText/Elements/memory.lua:62>",

Does this script need to be updated?\

**Comment by azuraji** [comment]
I would just disable the Memory module.
